channels:
- conda-forge
dependencies:
- python=3.9.19
- pip<=23.3.1
- pip:
  - mlflow==2.12.1
  - cloudpickle==2.2.1
  - dill==0.3.8
  - numpy==1.26.4
  - packaging==23.2
  - pandas==2.2.1
  - pyyaml==6.0.1
  - torch==2.1.1
  - tqdm==4.65.0
name: mlflow-env
